
<link href="/css/switch.css" rel="stylesheet" type="text/css">
<link href="/css/dropdown.css" rel="stylesheet" type="text/css">
<link href="/css/button.css" rel="stylesheet" type="text/css">

<script type="text/javascript">
function SelectChanged(flag) {
	if (flag !== undefined && flag) {
		document.getElementById('btn_list_save').disabled = true;
		return;
	}
	document.getElementById('btn_list_save').disabled = false;
}
function Save() {
	var data = new Array();
	var tr = $('#mlist_table').find('tr');
	for (var i = 1; i < tr.length; i ++) {
		var cells = tr[i].cells;
		var data_line = {
			'username': ((cells[0].childNodes[0] === undefined) ? '' : cells[0].childNodes[0].data),
			'real_name': ((cells[1].childNodes[0] === undefined) ? '' : cells[1].childNodes[0].data), 
			'email': ((cells[2].childNodes[0] === undefined) ? '' : cells[2].childNodes[0].data),
			'status': $('input:radio[name=status'+i+']:checked').val(),
			'id_role': cells[4].childNodes[1].childNodes[1].value
		};
		data[i-1] = data_line;
	}

    Jsoncallback('/auth/users/update', 
    	    function (json) {
		        if (json.err !== undefined && json.err != "") {
		            alert(json.err);
		            return false;
		        }
		        if (json.success !== undefined) {
		        	SelectChanged(true);
			        alert(json.success);
			        return true;
		        }
		        if (json.data === undefined) {
		    		return false;
	    		}
		        var data = json.data;
		        alert(data);// debug
	    	}, 
            'POST', 
            {'d': data, 'timestamp' : Date.parse(new Date())}, 
            'loading');
}
</script>

<span style="font-size: 20px;">用户管理</span><br/><br/>
<table id="mlist_table" class="table_manage">
    <thead><tr><th>username/用户名</th><th>real_name/真实姓名</th><th>email/邮箱</th><th>status/状态</th><th>role/角色</th></tr></thead>
    <tbody style="font-size: 13px">
    <?php $_i = 0; foreach($this->result as $row) { $_i ++; ?>
    <tr>
        <td style="color: #888;"><?php echo $row['username'] ?></td>
        <td style="color: #888;"><?php echo $row['real_name'] ?></td>
        <td style="color: #888;"><?php echo $row['email'] ?></td>
        <td>
		    <div class="switch-div">
		      <input type="radio" onchange="SelectChanged()" id="status_approved<?php echo $_i; ?>" class="switch-input" name="status<?php echo $_i; ?>" value="approved" <?php if($row['status'] == 'approved') echo 'checked'; ?>>
		      <label for="status_approved<?php echo $_i; ?>" class="switch-label switch-label-off">approved</label>
		      <input type="radio" onchange="SelectChanged()" id="status_unapproved<?php echo $_i; ?>" class="switch-input" name="status<?php echo $_i; ?>" value="unapproved" <?php if($row['status'] == 'unapproved') echo 'checked'; ?>>
		      <label for="status_unapproved<?php echo $_i; ?>" class="switch-label switch-label-on">unapproved</label>
		      <span class="switch-selection"></span>
		    </div>
        </td>
        <td>
			<div class="dropdown">
		      <select class="dropdown-select" onchange="SelectChanged()">
        		<?php foreach($this->rolenames as $id_role => $rolename) { ?>
        		<option value="<?php echo $id_role; ?>" <?php if($row['role'] == $rolename) { ?>selected<?php } ?> ><?php echo $rolename; ?></option>
        		<?php } ?>
		      </select>
		    </div>
        </td>
    </tr>
    <?php } ?>
    </tbody>
</table>
<div style="text-align:left; margin: 10px;">
<br/>
<button id="btn_list_save" type="button" disabled="disabled" onclick="Save()" class="bigbutton button-blue">保存</button>
</div>
