<link href="/css/profile.css" rel="stylesheet" type="text/css" />

<div>
<?php if (!isset($this->error) && !isset($this->success)) { ?>
<form accept-charset="UTF-8" action="/auth/index/forgetpassword" enctype="multipart/form-data" method="POST">
  <fieldset>
    <legend><span class="profile_title">忘记密码</span></legend>
    <hr style="border-color: rgb(240, 237, 237); margin: 0px; padding: 0px;" noshade="noshade"/><br/>
    <div class="div_profile_value">
    	<label class="label_profile_name" for="profile_email">请输入注册邮箱</label>
    	<div><input id="profile_email" name="profile_email" type="text" size="20" maxlength="85" /></div>
    </div><br/>
    <hr style="border-color: rgb(240, 237, 237); margin: 0px; padding: 0px;" noshade="noshade"/><br/>
    <div class="div_profile_value">
    	<label class="label_profile_name"></label>
    	<div><input type="submit" value="发送邮件" /></div>
    </div><br/>
  </fieldset>
</form>
<?php } ?>
</div>