
<link href="/css/auth.css" rel="stylesheet" type="text/css">
<script type="text/javascript">
<!--
$(document).ready(function() {
	var obj = $('#auth_login:first *:input[type=text]:first');
	obj.focus();
	obj.select();
});
//-->
</script>

<span class="div_auth_title">登录</span>
<hr style="border-color: rgb(240, 237, 237); margin: 0px; padding: 0px;" noshade="noshade"><br/>
<div class="div_auth">
	<form action="/auth/index/login" method="post" id="auth_login" enctype="application/x-www-form-urlencoded">
	<input type="hidden" name="redirect" value="<?php echo $this->redirect?>" />
	<div><label class="label_auth" for="username">用户名</label><input type="text" name="username" 
		value="<?php echo (isset($this->form->username)?$this->form->username:'');?>" /></div><br/>
	<div><label class="label_auth" for="password">密　码</label><input type="password" name="password" 
		value="" /></div><br/>
	<div><label class="label_auth" for="isremember"></label><input type="checkbox" name="isremember" 
		value="1" checked="checked" />
	<label class="label_auth_right">下次自动登录</label>
	</div><br/>
	<div><label class="label_auth"></label><input type="submit" value="登录" /><a class="a_auth" href="/auth/index/forgetpassword">忘记密码？</a></div>
	</form>
</div>
