<link href="/css/auth.css" rel="stylesheet" type="text/css">
<script type="text/javascript">
<!--
$(document).ready(function() {
	var obj = $('#auth_register:first *:input[type=text]:first');
	obj.focus();
	obj.select();
});
//-->
</script>

<?php if (!isset($this->success) || empty($this->success)) { ?>

<span class="div_auth_title">注册</span>
<hr style="border-color: rgb(240, 237, 237); margin: 0px; padding: 0px;" noshade="noshade"><br/>
<div class="div_auth">
	<form action="/auth/index/register" method="post" id="auth_register" enctype="application/x-www-form-urlencoded">
	
	<input type="hidden" name="redirect" value="<?php echo $this->redirect?>" />
	
	<div><label class="label_auth" for="real_name">名字</label><input type="text" name="real_name" 
		value="<?php echo (isset($this->form->real_name)?$this->form->real_name:'');?>" /></div><br/>
	
	<div><label class="label_auth" for="email">Email邮箱</label><input type="text" name="email" 
		value="<?php echo (isset($this->form->email)?$this->form->email:'');?>" /></div><br/>
	
	<div><label class="label_auth" for="emailAgain">再次确认邮箱</label><input type="text" name="emailAgain" 
		value="<?php echo (isset($this->form->emailAgain)?$this->form->emailAgain:'');?>" /></div><br/>
	
	<div><label class="label_auth" for="username">用户名</label><input type="text" name="username" 
		value="<?php echo (isset($this->form->username)?$this->form->username:'');?>" /></div><br/>
	
	<div><label class="label_auth" for="password">密码</label><input type="password" name="password" 
		value="<?php echo (isset($this->form->password)?htmlspecialchars($this->form->password):'');?>" /></div><br/>
	
	<div><label class="label_auth" for="passwordAgain">再次确认密码</label><input type="password" name="passwordAgain" 
		value="<?php echo (isset($this->form->passwordAgain)?htmlspecialchars($this->form->passwordAgain):'');?>" /></div><br/>
	
	<div><label class="label_auth"></label><input type="submit" value="注册" /></div>
	
	</form>
</div>

<?php } ?>
