<link href="/css/profile.css" rel="stylesheet" type="text/css" />

<div>
<?php if (!isset($this->error) && !isset($this->success)) { ?>
<form accept-charset="UTF-8" action="/auth/index/resetpassword" enctype="multipart/form-data" method="POST">
  <input type="hidden" name="str" value="<?php echo (empty($this->str)?'':$this->str); ?>"/>
  <input type="hidden" name="email" value="<?php echo (empty($this->email)?'':$this->email); ?>"/>
  <fieldset>
    <legend><span class="profile_title">重置密码</span></legend>
    <hr style="border-color: rgb(240, 237, 237); margin: 0px; padding: 0px;" noshade="noshade"/><br/>
    <div class="div_profile_value">
    	<label class="label_profile_name" for="profile_new_pwd">新密码</label>
    	<div><input id="profile_new_pwd" name="profile_new_pwd" type="password" size="20" maxlength="85" 
    		value="<?php echo (empty($this->profile_new_pwd)?'':$this->profile_new_pwd); ?>" /></div>
    </div><br/>
    <div class="div_profile_value">
    	<label class="label_profile_name" for="profile_new_pwd_again">再次确认新密码</label>
    	<div><input id="profile_new_pwd_again" name="profile_new_pwd_again" type="password" size="20" maxlength="85" 
    		value="<?php echo (empty($this->profile_new_pwd_again)?'':$this->profile_new_pwd_again); ?>" /></div>
    </div><br/>
    <hr style="border-color: rgb(240, 237, 237); margin: 0px; padding: 0px;" noshade="noshade"/><br/>
    <div class="div_profile_value">
    	<label class="label_profile_name"></label>
    	<div><input type="submit" value="确认修改" /></div>
    </div><br/>
  </fieldset>
</form>
<?php } ?>
</div>