
<link href="/css/switch.css" rel="stylesheet" type="text/css">
<link href="/css/dropdown.css" rel="stylesheet" type="text/css">
<link href="/css/button.css" rel="stylesheet" type="text/css">

<script type="text/javascript">

function SelectChanged(flag) {
	if (flag !== undefined && flag) {
		document.getElementById('btn_list_save').disabled = true;
		return;
	}
	document.getElementById('btn_list_save').disabled = false;
}
function SelectChangedValid() {
	if ('' == event.currentTarget.options[0].value) {
		event.currentTarget.options[0] = null;
	}
	SelectChanged();
}
function Save() {
	var data = new Array();
	var tr = $('#mlist_table').find('tr');
	for (var i = 1; i < tr.length; i ++) {
		var cells = tr[i].cells;
		var data_line = {
			'id': ((cells[0].childNodes[0] === undefined) ? '' : cells[0].childNodes[0].data),
			'id_role': cells[1].childNodes[1].childNodes[1].value,
			'id_resource': cells[2].childNodes[1].childNodes[1].value,
			'permission': $('input:radio[name=permission'+i+']:checked').val()
		};
		data[i-1] = data_line;
	}

    Jsoncallback('/auth/permissions/update', 
    	function (json) {
	        if (json.err !== undefined && json.err != "") {
	            alert(json.err);
	            return false;
	        }
	        if (json.success !== undefined) {
	        	SelectChanged(true);
		        alert(json.success);
		        return true;
	        }
	        if (json.data === undefined) {
	    		return false;
			}
		}, 
	    'POST', 
	    {'d': data, 'timestamp' : Date.parse(new Date())}, 
	    'loading');
}

function TblUnsetAddItem() {
	$("#btn_list_add").text("添加");
    $( "#btn_list_add" ).unbind( "click", TblCancelAddItem );
    $( "#btn_list_add" ).bind( "click", TblAddItem );
}

function TblCancelAddItem() {
	$("#mlist_table tbody>tr:last").remove();
	TblUnsetAddItem();
}

function TblAddItem() {
	var index_num = $('#mlist_table').find('tr').length;
	$("#mlist_table tbody").append("<tr><td></td>"
		+ "<td>\n"
		+ "<div class='dropdown'>\n"
		+ "<select class='dropdown-select' onchange='SelectChangedValid()'>"
		+ "<option value=''>--请选择角色--</option>"
		<?php foreach($this->rolenames as $id_role => $rolename) { ?>
		+ "<option value='<?php echo $id_role; ?>'><?php echo $rolename; ?></option>"
		<?php } ?>
		+ "</select>\n"
		+ "</div>\n"
		+"</td>\n"
		+ "<td>\n"
		+ "<div class='dropdown'>\n"
		+ "<select class='dropdown-select' onchange='SelectChangedValid()'>"
		+ "<option value=''>--请选择资源--</option>"
		<?php foreach($this->resourcenames as $id_resource => $resourcename) { ?>
		+ "<option value='<?php echo $id_resource; ?>'><?php echo $resourcename; ?></option>"
		<?php } ?>
		+ "</select>\n"
		+ "</div>\n"
		+ "</td>\n"
		+ "<td>\n"
		+ "<div class='switch-div'>\n"
		+ "  <input type='radio' onchange='SelectChanged()' id='permission_allow"+index_num+"' class='switch-input' name='permission"+index_num+"' value='allow' checked>\n"
		+ "  <label for='permission_allow"+index_num+"' class='switch-label switch-label-off'>allow</label>\n"
		+ "  <input type='radio' onchange='SelectChanged()' id='permission_deny"+index_num+"' class='switch-input' name='permission"+index_num+"' value='deny' >\n"
		+ "  <label for='permission_deny"+index_num+"' class='switch-label switch-label-on'>deny</label>\n"
		+ "  <span class='switch-selection'></span>\n"
		+ "</div>\n"
		+ "</td>\n"
		+ "<td><a href='#' onclick='tbl_additem_handler(event)' class='button button-gray'>确定</a></td></tr>");
	$("#mlist_table tbody>tr:last>td>input:first").focus();
    $( "#mlist_table input" ).keydown(function() {
        if (27 == event.which) { // ESC keyboard
        	TblCancelAddItem();
        } else if (13 == event.which) { // Enter keyboard
            $("#mlist_table tbody>tr:last button").trigger("click");
        }
	});
    $("#btn_list_add").text("取消");
    $( "#btn_list_add" ).unbind( "click", TblAddItem );
    $( "#btn_list_add" ).bind( "click", TblCancelAddItem );
}

function tbl_deleteitem_handler(event) {
	if (!confirm("确认要删除吗？")) {
		return false;
	}
	Jsoncallback('/auth/permissions/delete', 
	    function (json) {
	    	if (null == json) return false;
	        if (json.err !== undefined && json.err != "") {
	            alert(json.err);
	            document.location.reload();
	            return false;
	        }
	        if (json.success !== undefined) {
	        	SelectChanged(true);
	        }
    	}, 
        'POST', 
        {'d': '', 'timestamp' : Date.parse(new Date()), 
         'id': event.toElement.parentElement.parentElement.cells[0].childNodes[0].data}, 
        'loading');
	event.toElement.parentElement.parentElement.remove();
}

function tbl_additem_handler(event) {
	var index_num = $('#mlist_table').find('tr').length;
	Jsoncallback('/auth/permissions/add', 
	    function (json) {
	    	if (null == json) return false;
	        if (json.err !== undefined && json.err != "") {
	            alert(json.err);
	            return false;
	        }
	        if (json.success !== undefined) {
	        	SelectChanged(true);
		        // alert(json.success);
	        }
	        if (json.id === undefined) {
	    		return false;
    		}
	        var id = json.id;
	        $("#mlist_table tbody>tr:last>td:first").text(id);
	        $("#mlist_table tbody>tr:last select")[0].disabled = true;
	        $("#mlist_table tbody>tr:last select")[1].disabled = true;
	        $("#mlist_table tbody>tr:last>td")[4].innerHTML = "<a href='#' onclick='return tbl_deleteitem_handler(event)' class='button button-gray'>删除</a>";
    	}, 
        'POST',
        {'d': '', 'timestamp' : Date.parse(new Date()),
         'id_role': $("#mlist_table tbody>tr:last>td")[1].childNodes[1].childNodes[1].value,
         'id_resource': $("#mlist_table tbody>tr:last>td")[2].childNodes[1].childNodes[1].value,
         'permission': $("#mlist_table tbody>tr:last>td>div>input:radio[name=permission"+(index_num-1)+"]:checked").val()},
        'loading');
	TblUnsetAddItem();
}

$(function() {
})

</script>

<span style="font-size: 20px;">权限对照</span><br/><br/>
<table id="mlist_table" class="table_manage">
    <thead>
    <tr>
    	<th style="width:10%;">id/权限ID</th>
    	<th style="width:30%;">role/角色</th>
    	<th style="width:30%;">resource/资源</th>
    	<th style="width:20%;">permission/权限</th>
    	<th style="width:10%;"></th>
    </tr>
    </thead>
    <tbody style="font-size: 13px">
    <?php $_i = 0; foreach($this->result as $row) { $_i ++; ?>
    <tr>
        <td style="color: #888;"><?php echo $row['id'] ?></td>
        <td>
        	<div class="dropdown">
        	<select class="dropdown-select" onchange="SelectChanged()" disabled="disabled">
        		<?php foreach($this->rolenames as $id_role => $rolename) { ?>
        		<option value="<?php echo $id_role; ?>" <?php if($row['role'] == $rolename) { ?>selected<?php } ?> ><?php echo $rolename; ?></option>
        		<?php } ?>
        	</select>
        	</div>
        </td>
        <td>
        	<div class="dropdown">
        	<select class="dropdown-select" onchange="SelectChanged()" disabled="disabled">
        		<?php foreach($this->resourcenames as $id_resource => $resourcename) { ?>
        		<option value="<?php echo $id_resource; ?>" <?php if($row['resource'] == $resourcename) { ?>selected<?php } ?> ><?php echo $resourcename; ?></option>
        		<?php } ?>
        	</select>
        	</div>
        </td>
        <td>
			<div class="switch-div">
		      <input type="radio" onchange="SelectChanged()" id="permission_allow<?php echo $_i; ?>" class="switch-input" name="permission<?php echo $_i; ?>" value="allow" <?php if($row['permission'] == 'allow') echo 'checked'; ?>>
		      <label for="permission_allow<?php echo $_i; ?>" class="switch-label switch-label-off">allow</label>
		      <input type="radio" onchange="SelectChanged()" id="permission_deny<?php echo $_i; ?>" class="switch-input" name="permission<?php echo $_i; ?>" value="deny" <?php if($row['permission'] == 'deny') echo 'checked'; ?>>
		      <label for="permission_deny<?php echo $_i; ?>" class="switch-label switch-label-on">deny</label>
		      <span class="switch-selection"></span>
		    </div>
        </td>
        <td><a href="#" onclick="return tbl_deleteitem_handler(event)" class="button button-gray">删除</a></td>
    </tr>
    <?php } ?>
    </tbody>
</table>
<div style="text-align:left; margin: 10px;">
<br/>
<button id="btn_list_add" type="button" onclick="TblAddItem()" class="bigbutton button-blue">添加</button>&nbsp;&nbsp;
<button id="btn_list_save" type="button" disabled="disabled" onclick="Save()" class="bigbutton button-blue">保存</button>
</div>
