
<link href="/css/info.css" rel="stylesheet" type="text/css">

<span style="font-size: 20px; font-weight: bold; color: #2375BE;">加入比咕</span>
<hr style="border-color: rgb(240, 237, 237); margin: 0px; padding: 0px; margin-bottom: 10px;" noshade="noshade">

<div class="info_div">
<p><img src="/image/word_cloud.png" style="max-height: 200px;" /></p>
<p>目前创业计划还没启动，如果你有技术，有资源，有资金，我都很欢迎的。技术方面只要优秀就好，或许我不需要你的技术，但也可能给您一些好的推荐吧。
技术方面目前我们专注于自然语言处理和机器学习相关，资源方面希望有硬件存储资源方面的大亨，资金方面如果有投行、天使经验的更佳。</p>
<p>或许，我们可以先聊聊吧。</p>
<p></p>
</div>
