<script src="/include/ckeditor/ckeditor.js"></script>
<link type="text/css" rel="stylesheet" media="all" href="/include/SyntaxHighlighter/styles/shCore.css"></link>
<link type="text/css" rel="stylesheet" media="all" href="/include/SyntaxHighlighter/styles/shThemeDefault.css"></link>
<script src="/include/SyntaxHighlighter/scripts/shCore.js" type="text/javascript"></script>
<script src="/include/SyntaxHighlighter/scripts/shAutoloader.js" type="text/javascript"></script>
<script type="text/javascript">

function PostPublishHandler() {
	document.getElementById('post_form').action='/post/post/add';
	if ($('#post_title').val() == '') {
		alert('文章标题不能为空');
		return false;
	}
}

function PostPreviewHandler() {
	document.getElementById('post_form').action='/post/post/preview';
	if ($('#post_title').val() == '') {
		alert('文章标题不能为空');
		return false;
	}
}

function SelectChangedCascade() {
	Jsoncallback('/post/category/subcategory', 
    	function (json) {
	        if (json.err !== undefined && json.err != "") {
	            alert(json.err);
	            return false;
	        }
	        if (json.subcategorys === undefined) {
	    		return false;
			}
			if (json.subcategorys.length > 0) {
				var option_html = '<option value="0" selected="selected" disabled>--详细类别(可选)--</option>';
				for (var i = 0; i < json.subcategorys.length; i ++) {
					var new_option = '<option value="' + json.subcategorys[i] + '">' + json.subcategorys[i] + '</option>';
					option_html += new_option;
				}
				$("#post_select_subcategory").html(option_html);
				$("#post_select_subcategory").parent().fadeIn();
			} else {
				$("#post_select_subcategory").prop("selectedIndex", 0);
				$("#post_select_subcategory").parent().fadeOut();
			}
		}, 
	    'POST', 
	    {'d': '', 'timestamp' : Date.parse(new Date()), 
		 'category': $('#post_select_bigcategory').val()}, 
	    'loading');
}
</script>

<form action="/post/post/list" method="POST" id="post_form">
	<div>
		<label class="post_add_label">
		    <select class="post_add_select" id="post_select_bigcategory" name="post_select_bigcategory"
		    	 onchange="SelectChangedCascade()" >
		        <option value="0" selected="selected" disabled>--请选择一个类别--</option>
        		<?php foreach($this->bigcategorys as $cgname) { ?>
        		<option value="<?php echo $cgname; ?>" <?php if(!empty($this->result) && $this->result['category'] == $cgname) {echo 'selected';} ?>><?php echo $cgname; ?></option>
        		<?php } ?>
		    </select>
		</label>&nbsp;
		<label class="post_add_label" style="display:<?php echo (empty($this->subcategorys)?'none':'inline'); ?>;">
		    <select class="post_add_select" id="post_select_subcategory" name="post_select_subcategory">
		        <option value="0" selected="selected" disabled>--详细类别(可选)--</option>
        		<?php if (!empty($this->subcategorys)) foreach($this->subcategorys as $scgname) { ?>
        		<option value="<?php echo $scgname; ?>" <?php if($this->result['sub_category'] == $scgname) {echo 'selected';} ?>><?php echo $scgname; ?></option>
        		<?php } ?>
		    </select>
		</label>
	</div>
	<br/>
	<div>
		<input type="text" id="post_title" name="post_title" class="edit_title_input" placeholder="在这里输入一个响亮的标题"
			value="<?php if (!empty($this->result)) { echo $this->result['title']; } ?>"><br/><br/>
	</div>
	<p>
		<textarea class="ckeditor" cols="80" id="post_content" name="post_content" rows="10">
			<?php if (!empty($this->result)) { echo $this->result['content']; } ?>
		</textarea><br/>
	</p>
		<input type="hidden" id="post_id" name="post_id" value='<?php echo (!empty($this->result) && array_key_exists('id', $this->result)) ? $this->result['id'] : ''; ?>'>
	<p style="text-align: start;">
		<input type="submit" onclick="return PostPublishHandler();" value="保存">
		<input type="submit" onclick="return PostPreviewHandler();" value="预览">
	</p>
</form>

<!-- Idiot for SyntaxHighlighter must locate it in the foot! -->
<script src="/include/SyntaxHighlighter/load_syntaxhighlighter.js" type="text/javascript"></script>
