<script src="/include/ckeditor/ckeditor.js"></script>
<link type="text/css" rel="stylesheet" media="all" href="/include/SyntaxHighlighter/styles/shCore.css"></link>
<link type="text/css" rel="stylesheet" media="all" href="/include/SyntaxHighlighter/styles/shThemeDefault.css"></link>
<script src="/include/SyntaxHighlighter/scripts/shCore.js" type="text/javascript"></script>
<script src="/include/SyntaxHighlighter/scripts/shAutoloader.js" type="text/javascript"></script>
<script type="text/javascript">

///////////////////////////BEGIN OF AUTOSAVE////////////////////////////////////

var post_edit_struct = {
	createNew: function() {
		var _post_edit_struct = {};
		_post_edit_struct.post_select_bigcategory = $('#post_select_bigcategory').val();
		_post_edit_struct.post_select_subcategory = $('#post_select_subcategory').val();
		_post_edit_struct.post_title = $('#post_title').val();
		_post_edit_struct.post_content = $('#post_content').html().trim();
		return _post_edit_struct;
	}
}

var DEFAULT_DELAY_TIME = 3000;
var MAXIMUM_DELAY_TIME = 48000;
var g_post_edit_struct;
var autosave_try_delay = DEFAULT_DELAY_TIME;
var g_firsttime_diff = true;
var g_autosave_modified = false;
var g_interval;

$(document).ready(function() {
	g_interval = setInterval(CheckChange, autosave_try_delay);
	g_post_edit_struct = post_edit_struct.createNew();
});

function DiffPostStruct() {
	if (g_autosave_modified) return true;
	var editor = CKEDITOR.instances.post_content;
	var editor_value = CKEDITOR.tools.htmlEncode(editor.getData()).trim();
	if (g_firsttime_diff) { g_post_edit_struct.post_content = editor_value; g_firsttime_diff = false; }
	if ( (g_post_edit_struct.post_select_bigcategory == $('#post_select_bigcategory').val())
		&& (g_post_edit_struct.post_select_subcategory == $('#post_select_subcategory').val())
		&& (g_post_edit_struct.post_title == $('#post_title').val())
		&& (g_post_edit_struct.post_content == editor_value) ) {
		return false;
	}
	g_autosave_modified = true;
	return true;
}

function UpdatePostStruct() {
	var editor = CKEDITOR.instances.post_content;
	var editor_value = CKEDITOR.tools.htmlEncode(editor.getData()).trim();
	g_post_edit_struct.post_select_bigcategory = $('#post_select_bigcategory').val();
	g_post_edit_struct.post_select_subcategory = $('#post_select_subcategory').val();
	g_post_edit_struct.post_title = $('#post_title').val();
	g_post_edit_struct.post_content = editor_value;
	g_autosave_modified = false;
}

function CheckChange() {
	if (DiffPostStruct()) {
		// set autosave state
		$('.div_autosave_saved').hide(); $('.div_autosave_saving').show();
		// different then go to post
		var editor = CKEDITOR.instances.post_content;
		var editor_value = editor.getData();
		var d = {	post_id: $('#post_id').val(), 
					post_select_bigcategory: $('#post_select_bigcategory').val(), 
					post_select_subcategory: $('#post_select_subcategory').val(), 
					post_title: $('#post_title').val(), 
					post_content: editor_value };
		try {
			Jsoncallback_witherrorhandle('/post/post/save', ResponeJson, 'POST', d, null, TryDelay);
		} catch( err) {
			TryDelay(null, null, null);
		}
	}
}

function ResponeJson(json) {
	if (json.success != undefined && json.post_id != undefined) {
		$('#post_id').val(json.post_id);
		// set autosave state
		$('.div_autosave_saving').hide(); $('.div_autosave_saved').show();
		autosave_try_delay = DEFAULT_DELAY_TIME;
		clearInterval(g_interval);
		g_interval = setInterval(CheckChange, autosave_try_delay);
		UpdatePostStruct();
	}
}

function TryDelay(json, textStatus, errorThrown) {
	autosave_try_delay *= 2;
	if (autosave_try_delay > MAXIMUM_DELAY_TIME) { autosave_try_delay = MAXIMUM_DELAY_TIME; }
	clearInterval(g_interval);
	g_interval = setInterval(CheckChange, autosave_try_delay);
}

////////////////////////////END OF AUTOSAVE/////////////////////////////////////

function PostPublishHandler() {
	document.getElementById('post_form').action='/post/post/add';
	if ($('#post_title').val() == '') {
		alert('文章标题不能为空');
		return false;
	}
}

function SelectChangedCascade() {
	Jsoncallback('/post/category/subcategory', 
    	function (json) {
	        if (json.err !== undefined && json.err != "") {
	            alert(json.err);
	            return false;
	        }
	        if (json.subcategorys === undefined) {
	    		return false;
			}
			if (json.subcategorys.length > 0) {
				var option_html = '<option value="0" selected="selected" disabled>--详细类别(可选)--</option>';
				for (var i = 0; i < json.subcategorys.length; i ++) {
					var new_option = '<option value="' + json.subcategorys[i] + '">' + json.subcategorys[i] + '</option>';
					option_html += new_option;
				}
				$("#post_select_subcategory").html(option_html);
				$("#post_select_subcategory").parent().fadeIn();
			} else {
				$("#post_select_subcategory").prop("selectedIndex", 0);
				$("#post_select_subcategory").parent().fadeOut();
			}
		}, 
	    'POST', 
	    {'d': '', 'timestamp' : Date.parse(new Date()), 
		 'category': $('#post_select_bigcategory').val()}, 
	    'loading');
}
</script>

<form action="/post/post/list" method="POST" id="post_form">
	<div>
		<label class="post_add_label">
		    <select class="post_add_select" id="post_select_bigcategory" name="post_select_bigcategory"
		    	 onchange="SelectChangedCascade()" >
		        <option value="0" selected="selected" disabled>--请选择一个类别--</option>
        		<?php foreach($this->bigcategorys as $cgname) { ?>
        		<option value="<?php echo $cgname; ?>" <?php if(!empty($this->result) && $this->result['category'] == $cgname) {echo 'selected';} ?>><?php echo $cgname; ?></option>
        		<?php } ?>
		    </select>
		</label>&nbsp;
		<label class="post_add_label" style="display:<?php echo (empty($this->subcategorys)?'none':'inline'); ?>;">
		    <select class="post_add_select" id="post_select_subcategory" name="post_select_subcategory">
		        <option value="0" selected="selected" disabled>--详细类别(可选)--</option>
        		<?php if (!empty($this->subcategorys)) foreach($this->subcategorys as $scgname) { ?>
        		<option value="<?php echo $scgname; ?>" <?php if($this->result['sub_category'] == $scgname) {echo 'selected';} ?>><?php echo $scgname; ?></option>
        		<?php } ?>
		    </select>
		</label>
	</div>
	<div class="div_save_state">
		<div class="div_save_state_span div_autosave_start"><span>连接服务器</span></div>
		<div class="div_save_state_autosave post_autosave_start div_autosave_start"></div>
		<div class="div_save_state_span div_autosave_saving"><span>正在保存</span></div>
		<div class="div_save_state_autosave post_autosave_saving div_autosave_saving"></div>
		<div class="div_save_state_span div_autosave_saved"><span>已保存</span></div>
		<div class="div_save_state_autosave post_autosave_saved div_autosave_saved"></div>
	</div>
	<br/>
	<div>
		<input type="text" id="post_title" name="post_title" class="edit_title_input" placeholder="在这里输入一个响亮的标题"
			value="<?php if (!empty($this->result)) { echo $this->result['title']; } ?>"><br/>
	</div>
	<p>
		<textarea class="ckeditor" cols="80" id="post_content" name="post_content" rows="10">
			<?php if (!empty($this->result)) { echo $this->result['content']; } ?>
		</textarea>
	</p>
	<p style="text-align: start;">
		<input type="hidden" id="post_id" name="post_id" value='<?php echo (!empty($this->result) && array_key_exists('id', $this->result)) ? $this->result['id'] : ''; ?>'>
		<input type="submit" onclick="return PostPublishHandler();" value="保存">
	</p>
</form>

<!-- Idiot for SyntaxHighlighter must locate it in the foot! -->
<script src="/include/SyntaxHighlighter/load_syntaxhighlighter.js" type="text/javascript"></script>
