<link href="/css/pagination.css" rel="stylesheet" type="text/css">
<link href="/css/list_post.css" rel="stylesheet" type="text/css">

<script type="text/javascript">
<!--
function ConfirmHandler() {
	if (confirm("确认要删除吗？")) {
		return true;
	}
	return false;
}
//-->
</script>
<style>
<!--
-->
</style>

<div style="width: 100%; padding-right: 10px;">
	<?php if (empty($this->result)) { echo '<br/>找不到任何文章<br/>'; } ?>
    <?php foreach($this->result as $row) { ?>
    <div class="post_list_item">
    
    	<h4 class="h4_post_list_title">
    		<a href="/post/post/view?post_id=<?php echo $row['id'] ?>" title="<?php echo $row['title'] ?>">
    			<?php echo $row['title'] ?>
    		</a>
        </h4>
        
        <div class="div_post_list_info">
        	<!-- 跳转到个人博客列表 -->
        	<span><a href="/post/post/list?author=<?php echo $row['author'] ?>"><?php echo $row['author'] ?></a></span>｜
        	<span style="color: #999;"><?php echo $row['pub_datetime'] ?></span>
        	<?php if (!empty($row['category'])) { ?>｜
        	<span><a href="/post/post/list?category=<?php echo $row['category'] ?>"><?php echo $row['category'] ?></a></span>
        	<?php } ?>
        	<?php if (!empty($row['sub_category'])) { ?>/
        	<span><a href="/post/post/list?sub_category=<?php echo $row['sub_category'] ?>"><?php echo $row['sub_category'] ?></a></span>
        	<?php } ?>
        </div>
        
        <?php if (!empty($row['index_thumb'])) { ?>
        <div class="div_post_list_thumb">
        	<a href="/post/post/view?post_id=<?php echo $row['id'] ?>" title="<?php echo $row['title'] ?>">
        		<img src="<?php echo $row['index_thumb'] ?>"/>
        	</a>
        </div>
        <?php } ?>
        
        <div class="div_post_list_abstract" <?php echo (empty($row['index_thumb']) ? 'style="width:100%"' : "");  ?>>
        	<?php echo $row['abstract'] ?>
        </div>
        
        
    <?php $auth = Zend_Auth::getInstance();
    if ($auth->hasIdentity()) {
        $user = $auth->getStorage()->read();
        if ($user['username'] == $row['author']) { ?>
        <div class="div_post_list_edit">
        	<a href='/post/post/edit?post_id=<?php echo $row['id'] ?>'>编辑</a>
        	<a onclick="return ConfirmHandler();" href='/post/post/delete?post_id=<?php echo $row['id'] ?><?php echo (empty($this->category)?'':'&category='.$this->category); ?>'>删除</a>
        </div>
    <?php }
    } ?>
    </div>
    <?php } ?>
    
    <!-- 翻页页码 -->
<?php
	$_get_str = '';
	$_get_page = isset($_GET['page']) ? $_GET['page'] : 1;
	$_get_author = isset($_GET['author']) ? $_GET['author'] : null;
	$_get_category = isset($_GET['category']) ? $_GET['category'] : null;
	$_get_sub_category = isset($_GET['sub_category']) ? $_GET['sub_category'] : null;
	if (!empty($_get_author)) $_get_str .= ('&author=' . $_get_author);
	if (!empty($_get_category)) $_get_str .= ('&category=' . $_get_category);
	if (!empty($_get_sub_category)) $_get_str .= ('&sub_category=' . $_get_sub_category);
?>

<div class="div_pg_container">
    <div class="div_pg_list">
    <ul>
<?php 
$x = $_get_page;
$n = ceil($this->total_count/10);
$line = '';
if ($x <= 0 || $n <= 0 || $x > $n) {
	$line = '页码数出错，系统正在变更文章数量，请刷新页面，谢谢！';
	return $line;
}
/*
 显示第１页时不显示“上一页”按钮。
显示最后一页时不显示“下一页”按钮。
中间的页数最多这样放：(当前选择x，总页数n)
>10 ==> 1,2,...,x-1,x,x+1,...,n-1,n
如果x-1 <= 2+1，则不显示左中间省略号。左边显示1,2,3,4,5。最大不能超过n。
如果x+1 >= n-2，则不显示右中间省略号。右边显示n-4,n-3,n-2,n-1,n。最小不能小于1。
*/
if ($x > 1) echo '<li class="prev previous_page"><a rel="prev" href="/post/post/list?page='.($x-1).$_get_str.'">← 上一页</a></li>';

for ($i = 1, $c = 1; $i <= $n; ) {
	if($i == 3 && $x-1 > 2+1) {
		if ($n-4 > 3) {
			echo '<li class="disabled"><a><span class="gap">…</span></a></li>';
			if ($x+1 > $n-2) $i = $n - 4;
			else $i = $x - 1;
			continue;
		}
	}
	if ($x == $i) echo '<li class="active"><a>'.$i.'</a></li>';
	else echo '<li><a href="/post/post/list?page='.$i.$_get_str.'">'.$i.'</a></li>';
	$i ++; $c ++;
	
	if ($c == 5+1 && $x+1 < $n-2 && $i < $n-1) {
		echo '<li class="disabled"><a><span class="gap">…</span></a></li>';
		$i = $n - 1;
		continue;
	}
	if ($c > 7) break;
}

if ($x < $n) echo '<li class="next next_page "><a rel="next" href="/post/post/list?page='.($x+1).$_get_str.'">下一页 →</a></li>';
?>
		</ul>
    </div>
</div>

</div>