<link type="text/css" rel="stylesheet" media="all" href="/include/SyntaxHighlighter/styles/shCore.css"></link>
<link type="text/css" rel="stylesheet" media="all" href="/include/SyntaxHighlighter/styles/shThemeDefault.css"></link>
<script src="/include/SyntaxHighlighter/scripts/shCore.js" type="text/javascript"></script>
<script src="/include/SyntaxHighlighter/scripts/shAutoloader.js" type="text/javascript"></script>
<link href="/css/view_post.css" rel="stylesheet" type="text/css">
<link href="/css/view_comment.css" rel="stylesheet" type="text/css">
<script type="text/javascript" src="/js/comment.js" ></script>
<script type="text/javascript">
<!--
function ConfirmHandler() {
	if (confirm("确认要删除吗？")) {
		return true;
	}
	return false;
}
//-->
</script>

<?php if (empty($this->result)) {
	echo '<br/>找不到这篇文章<br/>';
} else { ?>

<div class="div_post_view_title">
	<h1><?php echo $this->result['title']; ?></h1>
</div>

<div class="div_post_view_info">
	<!-- 跳转到个人博客列表 -->
	<span><a href="/account/index/list"><?php echo $this->result['author'] ?></a></span>｜
	<span style="color: #999;"><?php echo $this->result['pub_datetime'] ?></span>
	<?php if (!empty($this->result['category'])) { ?>｜
	<span><a href="/post/post/list?category=<?php echo $this->result['category'] ?>"><?php echo $this->result['category'] ?></a></span>
	<?php } ?>
	<?php if (!empty($this->result['sub_category'])) { ?>/
	<span><a href="/post/post/list?sub_category=<?php echo $this->result['sub_category'] ?>"><?php echo $this->result['sub_category'] ?></a></span>
	<?php } ?>
</div>

<div class="div_post_view_abstract">
	<?php echo $this->result['content'] ?>
</div>

<?php if (array_key_exists('id', $this->result) && !empty($this->result['id'])) { ?>
	<?php $auth = Zend_Auth::getInstance();
	if ($auth->hasIdentity()) {
	    $user = $auth->getStorage()->read();
	    if ($user['username'] == $this->result['author']) { ?>
	    <div class="div_post_view_edit">
	    	<a href='/post/post/edit?post_id=<?php echo $this->result['id'] ?>'>编辑</a>
	    	<a onclick="return ConfirmHandler();" href='/post/post/delete?post_id=<?php echo $this->result['id'] ?>'>删除</a>
	    </div>
	<?php }
	} ?>
<?php } ?>

<?php if (empty($this->preview)) { ?>
	<!-- 评论发表及列表 -->
<script type="text/javascript">
<!--
String.prototype.replaceAll = function(reallyDo, replaceWith, ignoreCase) {
    if (!RegExp.prototype.isPrototypeOf(reallyDo)) {
        return this.replace(new RegExp(reallyDo, (ignoreCase ? "gi": "g")), replaceWith);
    } else {
        return this.replace(reallyDo, replaceWith);
    }
}

Date.prototype.format = function(format) //author: meizz
{
  var o = {
    "M+" : this.getMonth()+1, //month
    "d+" : this.getDate(),    //day
    "h+" : this.getHours(),   //hour
    "m+" : this.getMinutes(), //minute
    "s+" : this.getSeconds(), //second
    "q+" : Math.floor((this.getMonth()+3)/3),  //quarter
    "S" : this.getMilliseconds() //millisecond
  }

  if(/(y+)/.test(format)) format=format.replace(RegExp.$1,
    (this.getFullYear()+"").substr(4 - RegExp.$1.length));
  for(var k in o)if(new RegExp("("+ k +")").test(format))
    format = format.replace(RegExp.$1,
      RegExp.$1.length==1 ? o[k] :
        ("00"+ o[k]).substr((""+ o[k]).length));
  return format;
}

function _AppendCommentItemIntoList(author, avatar, content, date, id) {
	if (avatar == '') avatar = '/image/default_avatar.jpg';
	var new_comment = '';
	new_comment += "<div class='div_comment_item' id='comment_item_"+id+"'>";
	new_comment += "	<div class='div_comment_avatar'>";
	new_comment += "      <a ";
	if (author != '' && author != "匿名") new_comment += (" href='/profile/comment/index?username="+author+"'");
	new_comment += ">";
	new_comment += "        <img src='"+avatar+"' style='width:48px;height:48px;'>";
	new_comment += "      </a>";
	new_comment += "    </div>";
	new_comment += "    <div class='comment_list_right'>";
	new_comment += "        <div class='comment_list_right_title'>";
	new_comment += "            <span>";
	new_comment += "                <a ";
	if (author != '' && author != "匿名") new_comment += (" href='/profile/comment/index?username="+author+"'");
	new_comment += " class='uname' target='_blank'>"+author+"</a>";
	new_comment += "            </span>";
	new_comment += "            <div style='float:right'>";
	new_comment += "                <em style='color: rgb(108, 115, 122); margin-right: 10px;'>"+date+"</em>";
	new_comment += "            </div>";
	new_comment += "        </div>";
	new_comment += "        <div class='comment_list_content'><p>"+content+"</p></div>";
	new_comment += "    </div>";
	if (author == '<?php echo $this->username; ?>') {
		new_comment += "<div class='comment_list_edit'>";
		new_comment += "<a onclick=\"return ConfirmDeleteCommentHandler(\'"+id+"\');\" href='/post/comment/delete'>删除</a>";
		new_comment += "</div>";
	}
	new_comment += "</div>";
	
	
	$('#view_comment_list').append(new_comment);
}

function CommentAddHandler() {
	Jsoncallback('/post/comment/add', 
    	function (json) {
	        if (json.err !== undefined && json.err != "") {
	            alert(json.err);
	            return false;
	        }
	        if (json.success === undefined) {
	    		return false;
			}
			if (json.id !== undefined) {
				var nowdate = new Date().format("yyyy-MM-dd h:mm:ss");
				var author = '<?php echo (!empty($this->username))?$this->username:'匿名';?>';
				var content = $('#comment_content').val();
				content = content.replaceAll('\n', '<br/>');
				_AppendCommentItemIntoList(author, '<?php echo (!empty($this->avatar))?$this->avatar:'';?>', content, nowdate, json.id);
				$('#comment_content').val("");
			} else {
				alert('添加评论失败');
			}
		}, 
	    'POST', 
	    {'d': '', 'timestamp' : Date.parse(new Date()), 
		 'comment_id_post': '<?php echo (array_key_exists('id', $this->result))?$this->result['id']:'';?>', 
		 'comment_author': '<?php echo (!empty($this->username))?$this->username:'';?>', 
		 'comment_content': $('#comment_content').val() }, 
	    'loading');
    
    return false;
}

function CommentListHandler() {
	Jsoncallback('/post/comment/list', 
		function (json) {
		    if (json.err !== undefined && json.err != "") {
		        alert(json.err);
		        return false;
		    }
		    if (json.success === undefined) {
				return false;
			}
			if (json.d !== undefined) {
				var d = json.d;
				$('#view_comment_list').html('');
				for (var i = 0; i < d.length; i ++) {
					// console.log(d[i].content);
					_AppendCommentItemIntoList(('' != d[i].author ? d[i].author : '匿名'), 
						d[i].avatar, d[i].content, d[i].pub_datetime, d[i].id);
				}
				$('#comment_content').val("");
			} else {
				// alert('加载评论失败');
			}
		}, 
		'POST', 
		{'d': '', 'timestamp' : Date.parse(new Date()), 
		'comment_id_post': '<?php echo (array_key_exists('id', $this->result))?$this->result['id']:'';?>' }, 
		'loading');

    return false;
}

$(document).ready(function() {
	CommentListHandler();
});

//-->
</script>

<div class="div_comment">
<h5 class="btn-block tohide sep30">文章评论</h5>

<!-- 评论列表 -->
<div class="div_comment_list" id="view_comment_list">
<!-- 
<div class="div_comment_item" id="comment_item_37">
	<div style="float:left; width: 10%;">
      <a href="/firstboy0513">
        <img alt="firstboy" src="/util/jquery_php_avatar/thumb/afa924407f7a3f81f4d5acae318b2d63.png" style="width:48px;height:48px;">
      </a>
    </div>
    <div class="comment_list_right">
        <div class="comment_list_right_title">
            <span>
                <a href="/profile/comment/index?username=admin" class="uname" target="_blank">admin</a>
            </span>
            <div style="float:right">
                <em style="color: rgb(108, 115, 122); margin-right: 10px;">2013-10-25 13:11:13</em>
            </div>
        </div>
        <div class="comment_list_content"><p>此前 Keen IO 曾在种</p></div>
    </div>
    <div class="comment_list_edit">
        <a onclick="return ConfirmDeleteCommentHandler('37');" href="/post/comment/delete">删除</a>
    </div>
</div>
 -->
</div>


<div class="div_comment_add">
	<div class="pull-left face">
	    <a class="ulink" target="_blank" 
	    	<?php echo (!empty($this->username))?'href="/profile/comment/index?username='.$this->username.'"':'';?>>
	        <img src="<?php echo (!empty($this->avatar))?$this->avatar:'/image/default_avatar.jpg';?>" 
	        	style="width:48px;height:48px;border-radius: 6px;margin-left: 10px;float: left;" 
	        	title="<?php echo (!empty($this->username))?$this->username:'匿名';?>" />
	    </a>
	</div>
    <span class="name"><a <?php echo (!empty($this->username))?'href="/profile/comment/index?username='.$this->username.'"':'';?>
    	class="uname" target="_blank"><?php echo (!empty($this->username))?$this->username:'匿名';?></a></span>
    <form accept-charset="UTF-8" action="/post/comment/add" data-remote="true" id="form_comment" method="POST">
    <textarea class="topic_editor span10" id="comment_content" name="comment_content" 
        placeholder="在这里输入评论……" tabindex="1" 
        onpropertychange="{if (this.scrollHeight > 50) this.style.height=(this.scrollHeight)+'px'}" 
        oninput="{if (this.scrollHeight > 50) this.style.height=(this.scrollHeight)+'px'}"></textarea>
    <input type="submit" class="btn_comment_submit" onclick="return CommentAddHandler();" value="评论"/>
    </form>
</div>

</div><!-- 文章评论结束div -->

<?php } // end of preview ?>
<?php } // end of result ?>

<!-- Idiot for SyntaxHighlighter must locate it in the foot! -->
<script src="/include/SyntaxHighlighter/load_syntaxhighlighter.js" type="text/javascript"></script>
