<!DOCTYPE>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<script type="text/javascript">

function _AppendCategoryItemIntoList(category) {
	var new_item = '';
	new_item += '<li class="menu_category"><div class="menuText">';
	new_item += '<a href="/post/post/list?category=';
	new_item += category;
	new_item += '">';
	new_item += category;
	new_item += '</a>';
	new_item += '</div><i class="icon-home"></i></li>';
	$('#ul_category_list').append(new_item);
}

function _AppendSubcategoryItemIntoList(subcategory, category, currflag) {
	var new_item = '';
	new_item += '<li><a ';
	if (currflag) new_item += " style=\'background:#258CFF;color:#fff;padding: 10px 15px;\' ";
	new_item += 'href="/post/post/list?category=';
	new_item += category;
	new_item += '&sub_category=';
	new_item += subcategory;
	new_item += '">';
	new_item += subcategory;
	new_item += '</a></li>';
	$('#ul_subcategory_list').append(new_item);
}

function CategoryListHandler(vcurr_category, vcurr_subcategory) {
	Jsoncallback('/post/category/list', 
		function (json) {
		    if (json.err != undefined && json.err != "") {
		        alert(json.err);
		        return false;
		    }
		    if (json.success == undefined) {
				return false;
			}
			if (json.d !== undefined) {
				var d = json.d;
				$('#ul_category_list>.menu_category').remove();
				if (vcurr_category == '' && d.length > 0) {
					curr_category = d[0].category;
				} else {
					curr_category = vcurr_category;
				}
				for (var i = 0; i < d.length; i ++) {
					_AppendCategoryItemIntoList(d[i].category);
					if (curr_category == d[i].category) {
						var subcategorys = d[i].subcategorys;
						$('#ul_subcategory_list>li').remove();
						if (subcategorys.length == 0) {
							$('#div_subcategory').fadeOut();
						} else {
							$('#div_subcategory').fadeIn();
						}
						for (var j = 0; j < subcategorys.length; j ++) {
							_AppendSubcategoryItemIntoList(subcategorys[j], 
								d[i].category, (subcategorys[j] == vcurr_subcategory));
						}
					}
				}
				// set font-weight to bold which category is selected
				if (vcurr_category != '') {
					// $("#ul_category_list a").filter(":not(.menuText_a_hover)").css('font-size', '16px');
					// $("#ul_category_list a").filter(":not(.menuText_a_hover)").css('text-shadow', '1px 1px 1px rgba(255,255,255,.3),2px 2px 3px rgba(0,0,0,.3)');
					// $("#ul_category_list a").filter(":not(.menuText_a_hover)").css('background-color', 'rgba(190, 183, 183, 0)');
					$("#ul_category_list a").filter(":contains('"+vcurr_category+"')").css('font-size', '18px');
					$("#ul_category_list a").filter(":contains('"+vcurr_category+"')").css('text-shadow', '1px 1px 1px rgba(205,205,205,.8),2px 2px 3px rgba(10,10,10,.8)');
					// $("#ul_category_list a").filter(":contains('"+vcurr_category+"')").css('background-color', 'rgba(190, 183, 183, 0.34)');
				}
			} else {
				alert('加载类别失败');
			}
		}, 
		'POST', 
		{'d': '', 'timestamp' : Date.parse(new Date()) }, 
		'loading');

    return false;
}

$(document).ready(function() {
	var curr_category = '<?php echo isset($_GET['category']) ? $_GET['category'] 
		: (isset($this->category) ? $this->category : ''); ?>';
	var curr_subcategory = '<?php echo isset($_GET['sub_category']) ? $_GET['sub_category'] 
		: (isset($this->sub_category) ? $this->sub_category : ''); ?>';
	CategoryListHandler(curr_category, curr_subcategory);
});

</script>
</head>
<body>

<div class="left_div">
<nav class="sideBar hidden-phone pull-left">
<ul data-spy="affix" class="side_nav affix" id="ul_category_list">
    <li>
        <div class="menuText">
        <a href="/">
            <img width="200" height="65" src="/image/bigu.png" alt="比咕网" title="点击回到比咕网首页">
        </a>
        </div>
    </li>
    <!-- 
    <li class="menu_category"><figure>
        <div class="menuText">
            <a href="/">搜索技术</a>
        </div>
        <i class="icon-home"></i>
    </figure></li>
    
    <li class="menu_category"><figure>
        <div class="menuText">
            <a href="/post/post/list">自然语言处理</a>
        </div>
        <i class="icon-flag"></i>
    </figure></li>
    
    <li class="menu_category"><figure>
        <div class="menuText">
            <a href="/topics">互联网金融</a>
        </div>
        <i class="icon-group"></i>
    </figure></li>
    
    <li class="menu_category"><figure>
        <div class="menuText">
            <a href="/topics">编程</a>
        </div>
        <i class="icon-group"></i>
    </figure></li>
    
    <li class="menu_category"><figure>
        <div class="menuText">
            <a href="/topics">比咕实验室</a>
        </div>
        <i class="icon-group"></i>
    </figure></li>
    -->
    </ul>
</nav>
</div>

</body>
</html>