<!DOCTYPE>
<html>
	<head>
		<meta charset="UTF-8" />
		<link href="/css/my.css" rel="stylesheet" type="text/css" />
		<script type="text/javascript" src="/js/jquery.js" ></script>
		<script type="text/javascript" src="/js/util.js" ></script>
		<script type="text/javascript" src="/js/my.js" ></script>
		<?php if (!empty($this->manage)) { ?>
		<link href="/css/manage.css" rel="stylesheet" type="text/css">
		<?php } ?>
		<?php if (!empty($this->editor)) { ?>
		<link href="/css/editor.css" rel="stylesheet" type="text/css">
		<?php } ?>
	</head>
	
	<body>
<section>
	<?php if (!empty($this->manage)) { ?>
	<!-- 管理左面板 -->
	<?php include(APPLICATION_PATH . "/../public/html/left_mnav.html"); ?>
	<?php } else if (!empty($this->profile)) { ?>
	<!-- 个人中心面板 -->
	<?php include(APPLICATION_PATH . "/../public/html/left_pnav.html"); ?>
	<?php } else { ?>
	<!-- 主页左面板 -->
	<?php include(APPLICATION_PATH . "/../public/html/left_nav.phtml"); ?>
	<?php } ?>
	
	<!-- 右边面板(采用table作布局) -->
	<div class="span10 content borBox pull-right">
	<?php if (!empty($this->manage)) { ?>
	
	<!-- 管理右边面板 -->
	<?php if (!empty($this->error)) { ?>Error: <?php echo $this->error; ?><br/><?php } ?>
	<?php if (!empty($this->success)) { ?>Success: <?php echo $this->success; ?><br/><?php } ?>
	<?php echo $this->layout()->content; ?>
	<?php } else { ?>
	  <table border="1" style="width: 100%;">
	  	<tr>
		  	<td style="width: 672px;">
		  		<!-- 右上广告图块 -->
		  		<?php include(APPLICATION_PATH . "/../public/html/top_ad.html"); ?>
		  	</td>
		  	<td>
		  		<!-- 右上登录链接块 -->
		  		<?php include(APPLICATION_PATH . "/../public/html/top_links.html"); ?>
		  	</td>
	  	</tr>
	  	<?php if (empty($this->editor)) { ?>
	  	<tr>
		  	<td style="height: 45px;">
		  		<!-- 右上子导航栏 -->
		  		<?php include(APPLICATION_PATH . "/../public/html/top_subnav.phtml"); ?>
		  	</td>
		  	<td>
		  		<!-- 右上子搜索框 -->
		  		<?php include(APPLICATION_PATH . "/../public/html/top_search.html"); ?>
		  	</td>
	  	</tr>
	  	<?php } // end for editor judgement ?>
	  	<tr>
		  	<td colspan="<?php echo (empty($this->editor)) ? 1 : 2; ?>" style="text-align:left;align:left;">
		  		<div <?php echo (empty($this->editor)) ? 'style="width: 665px"' : ''; ?>>
		  		<!-- 右中内容正文/列表栏 -->
				<?php if (!empty($this->error)) { ?>Error: <?php echo $this->error; ?><br/><?php } ?>
				<?php if (!empty($this->success)) { ?>Success: <?php echo $this->success; ?><br/><?php } ?>
				<?php echo $this->layout()->content; ?>
				</div>
		  	</td>
		  	<?php if (empty($this->editor)) { ?>
		  	<td>
		  		<?php include(APPLICATION_PATH . "/../public/html/right_panel.html"); ?>
		  	</td>
		  	<?php } // end for editor judgement ?>
	  	</tr>
	</table>
	
	<!-- 右下页脚脚注 -->
	<?php include(APPLICATION_PATH . "/../public/html/foot.html"); ?>
	<?php } ?>
	</div>
</section>

<?php include(APPLICATION_PATH . "/../public/html/loading.html"); ?>
</body>
</html>