<!DOCTYPE>
<html>
	<head>
		<meta charset="UTF-8" />
		<title>比咕网 | 关注搜索和自然语言处理技术</title>
		<meta name="keywords" content="比咕, 比咕网, bigu, 自然语言处理, 搜索引擎, 大数据, 数据挖掘, 情感语义分析, 中文分词, 文本分类, 文本聚类" />
		<meta name="description" content="比咕网是一个关注搜索和自然语言处理技术的科技博客" />
		<link href="/css/my.css" rel="stylesheet" type="text/css" />
		<link href="/css/message.css" rel="stylesheet" type="text/css">
		<script type="text/javascript" src="/js/jquery.js" ></script>
		<script type="text/javascript" src="/js/util.js" ></script>
		<script type="text/javascript" src="/js/my.js" ></script>
		<?php if (!empty($this->manage)) { ?>
		<link href="/css/manage.css" rel="stylesheet" type="text/css">
		<?php } ?>
		<?php if (!empty($this->editor)) { ?>
		<link href="/css/editor.css" rel="stylesheet" type="text/css">
		<?php } ?>
	</head>
	
	<body>
	
<table border="1" style="width: 100%;">
<tr><td style="width:20%; height: 100%; position: fixed;">

	<?php if (!empty($this->manage)) { ?>
	<!-- 管理左面板 -->
	<?php include(APPLICATION_PATH . "/../public/html/left_mnav.html"); ?>
	<?php } else if (!empty($this->profile)) { ?>
	<!-- 个人中心面板 -->
	<?php include(APPLICATION_PATH . "/../public/html/left_pnav.html"); ?>
	<?php } else { ?>
	<!-- 主页左面板 -->
	<?php include(APPLICATION_PATH . "/../public/html/left_nav.phtml"); ?>
	<?php } ?>
	
</td><td style="width:80%; height: 100%; text-align: right;">
	
	<!-- 右边面板(采用table作布局) -->
	<div class="span10 content borBox pull-right">
	<?php if (!empty($this->manage)) { ?>
	
	<!-- 管理右边面板 -->
	<?php if (!empty($this->error)) {
		echo "<div class=\"div_message\"><span style=\"color:red\">【ERROR】：".$this->error."</span></div><br/>\n";
	} ?>
	<?php if (!empty($this->success)) {
		echo "<div class=\"div_message\"><span style=\"color:green\">【SUCCESS】：".$this->success."</span></div><br/>\n";
	} ?>
	<?php echo $this->layout()->content; ?>
	<?php } else { ?>
	  <table border="1" style="width: 100%;">
	  	<tr>
		  	<td style="width: 70%; padding-right: 10px;">
		  		<!-- 右上广告图块 -->
		  		<?php include(APPLICATION_PATH . "/../public/html/top_ad.html"); ?>
		  	</td>
		  	<td style="width: 30%; ">
		  		<!-- 右上登录链接块 -->
		  		<?php include(APPLICATION_PATH . "/../public/html/top_links.html"); ?>
		  	</td>
	  	</tr>
	  	<?php if (empty($this->editor)) { ?>
	  	<tr>
		  	<td style="width: 70%; padding-right: 10px; height: 45px;">
		  		<!-- 右上子导航栏 -->
		  		<?php include(APPLICATION_PATH . "/../public/html/top_subnav.phtml"); ?>
		  	</td>
		  	<td>
		  		<!-- 右上子搜索框 -->
		  		<?php include(APPLICATION_PATH . "/../public/html/top_search.html"); ?>
		  	</td>
	  	</tr>
	  	<?php } // end for editor judgement ?>
	  	<tr>
		  	<td colspan="<?php echo (empty($this->editor)) ? 1 : 2; ?>" style="text-align:left;align:left;width: 70%;padding-right:10px;">
		  		<div <?php echo (empty($this->editor)) ? 'style="width: 100%"' : ''; ?>>
		  		<!-- 右中内容正文/列表栏 -->
				<?php if (!empty($this->error)) {
					echo "<div class=\"div_message\"><span style=\"color:red\">【ERROR】：".$this->error."</span></div><br/>\n";
				} ?>
				<?php if (!empty($this->success)) {
					echo "<div class=\"div_message\"><span style=\"color:green\">【SUCCESS】：".$this->success."</span></div><br/>\n";
				} ?>
				<?php echo $this->layout()->content; ?>
				</div>
		  	</td>
		  	<?php if (empty($this->editor)) { ?>
		  	<td>
		  		<?php include(APPLICATION_PATH . "/../public/html/right_panel.html"); ?>
		  	</td>
		  	<?php } // end for editor judgement ?>
	  	</tr>
	</table>
	
	<!-- 右下页脚脚注 -->
	<?php include(APPLICATION_PATH . "/../public/html/foot.html"); ?>
	<?php } ?>
	</div>
	
</td></tr>
</table>

<?php include(APPLICATION_PATH . "/../public/html/loading.html"); ?>
</body>
</html>