<!DOCTYPE>
<html>
<head>
	<!-- <meta http-equiv="refresh" content="5;url=/"> 不要跳转 -->
	<meta charset="UTF-8">
	<title>404 page | 比咕网</title>
	<meta name="keywords" content="比咕, 比咕网, bigu, 自然语言处理, 搜索引擎, 大数据, 数据挖掘, 情感语义分析, 中文分词, 文本分类, 文本聚类" />
	<meta name="description" content="比咕网是一个关注搜索和自然语言处理技术的科技博客" />
	<link href="/css/my.css" rel="stylesheet" type="text/css" />
	<link href="/css/beautify.css" rel="stylesheet" type="text/css" />
</head>

<body>

<div class="shop-global-error">
    <h2>您访问的地址不存在，404，你懂得</h2>
    <br/>
    <a href="/" class="btn_beautify btn-home">去首页</a>
    <a href="javascript:;" onclick="history.go(-1);" class="btn_beautify btn-dake">返回上一页</a>
	</p>
</div>

</body>
</html>
