<script type="text/javascript">
// document.addEventListener("dblclick",function(){
// 	if(event.srcElement.tagName.toLowerCase() == "td"){
// 		alert('halo!');
// 		// changeToEdit(event.srcElement)
// 	}
// });
function SelectChanged(flag) {
	if (typeof flag !== 'undefined' && flag) {
		document.getElementById('btn_list_save').disabled = true;
		return;
	}
	document.getElementById('btn_list_save').disabled = false;
}
function Save() {
	var data = new Array();
	var tr = $('#mlist_table').find('tr');
	for (var i = 1; i < tr.length; i ++) {
		var cells = tr[i].cells;
		var data_line = {
			'username': ((typeof cells[0].childNodes[0] === 'undefined') ? '' : cells[0].childNodes[0].data),
			'real_name': ((typeof cells[1].childNodes[0] === 'undefined') ? '' : cells[1].childNodes[0].data), 
			'email': ((typeof cells[2].childNodes[0] === 'undefined') ? '' : cells[2].childNodes[0].data),
			'status': cells[3].childNodes[1].value,
			'id_role': cells[4].childNodes[1].value
		};
		data[i-1] = data_line;
	}

    Jsoncallback('/auth/users/update', 
    	    function (json) {
		        if (typeof json.err !== 'undefined' && json.err != "") {
		            alert(json.err);
		            return false;
		        }
		        if (typeof json.success !== 'undefined') {
		        	SelectChanged(true);
			        alert(json.success);
			        return true;
		        }
		        if (typeof json.data === 'undefined') {
		    		return false;
	    		}
		        var data = json.data;
		        alert(data);// debug
	    	}, 
            'POST', 
            {'d': data, 'timestamp' : Date.parse(new Date())}, 
            'loading');
}

$(function() {
    $("tbody>tr>td").dblclick(function(){
        // the first id column can not be editable
        if (event.srcElement.cellIndex == 0) {
            return;
        }
        SelectChanged();
        
        var inval = $(this).html();
        
        $(this).html("<input type='text' style='width:100%;text-align:right;' value='"+inval+"'>");
        $(this).children().focus();
        
        $(this).children().focusout(function() {
            var editval = $(this).val();
            $(this).parent().html(editval);
        })
    })
})

</script>

<style>
.table_manage {
border-width: 5px 5px 5px 5px;
border-color: blue rgb(25%,35%,45%) #909090 red;
border-spacing: 10px;
border-style: solid;
border-bottom:1px #999999 solid;
}
.table_manage tr>td, .table_manage tr>th {
border:1px solid #ff0000;
}
.table_manage input {
	text-align: left;
}
</style>

<span style="font-size: 20px;">角色管理</span><br/><br/>
<table id="mlist_table" class="table_manage">
    <thead>
    <tr>
    	<th style="width:10%;">id/角色ID</th>
    	<th style="width:60%;">role/角色</th>
    	<th style="width:30%;">id_parent/继承的父角色ID</th>
    </tr>
    </thead>
    <tbody>
    <?php foreach($this->result as $row) { ?>
    <tr>
        <td><?php echo $row['id'] ?></td>
        <td><?php echo $row['role'] ?></td>
        <td><?php echo $row['id_parent'] ?></td>
    </tr>
    <?php } ?>
    </tbody>
</table>

<button id="btn_list_save" type="button" disabled="disabled" onclick="Save()">保存</button>
